### ISSUE TITLE
Malformed Webpurify response

### ISSUE THREAD

**Issue by EntropyAu** [mileszim/webpurify#9]
Hi - many thanks for the library :) I've encountered one issue though (which I haven't had a chance to dig into yet) - when passed chinese language characters (eg. 網站有中、英文版本，也有繁、簡體版，可通過每頁左上角的連結隨時調整) I get the error "Malformed Webpurify response". 

I believe WebPurify doesn't support Chinese language (it's in beta), but I wouldn't expect a Malformed response error. Any ideas?

**Comment by mileszim** [comment]
"Malformed webpurify response" is thrown here https://github.com/mileszim/webpurify/blob/master/src/webpurify.js#L105 when the response is not parsable. If you believe it is, feel free to submit a PR updating how responses are handled.
